title: Swaroop2sky
author: S2Sofficial
email: swaroop2skyofficial@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Here we do very amazing things and we live in a different dimension of the world. 
  
  We learn, teach, code, guide and elaborate things
  in the possible easiest way in least time. 
  Learn more in small amount of time. 
  **Swaroop2sky**

# social links
twitter_username: swaroop2sky # DO NOT include the @ character, or else the build will fail!
github_username:  S2Sofficial # DO NOT include the @ character, or else the build will fail!
instagram_username: swaroop2sky 
show_excerpts: true # set to false to remove excerpts on the homepage
